#!/bin/bash

VOLUME=$1

SINK=`pacmd list-sinks | grep "* index: " | cut -b12 -`
if [ $1 == "0" ]; then
	pactl set-sink-mute $SINK toggle
else
	pactl set-sink-volume $SINK $VOLUME
fi

#for SINK in `pacmd list-sinks | grep "index:" | cut -b12-`
#do
#	if [ $1 == "0" ]; then
#		pactl set-sink-mute $SINK toggle
#	else
#		pactl set-sink-volume $SINK $VOLUME
#	fi
#done
