#!/bin/sh
# config_file_path=~/.config/bspwm/bspwmrc

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

bspc config border_width            2
bspc config window_gap              0
bspc config focused_border_color    '#98971a'
bspc config normal_border_color     '#282828'

bspc config split_ratio             0.5
bspc config borderless_monocle      true
bspc config gapless_monocle         true

$HOME/.config/polybar/launch.sh
~/.fehbg
