#!/bin/bash
# ~/.config/bspwm/bspwmrc

pgrep -x sxhkd > /dev/null || sxhkd &

if [[ $(xrandr | grep 'HDMI-1') == *'disconnected'* ]]; then
    echo 'disconnected'
    xrandr --output HDMI-1 --off
    # bspc monitor eDP-1 -d 1 2 3 4
else
    echo 'connected'
    # xrandr --output HDMI-1 --right-of eDP-1 --auto
    xrandr --output HDMI-1 --same-as eDP-1 --auto
    # bspc monitor eDP-1 -d 1 2 3 4
    # bspc monitor HDMI-1 -d 5 6 7 8
fi

#I bspc config remove_unplugged_monitors true
#I bspc config remove_disabled_monitors true

bspc monitor -d 1 2 3 4 0

bspc config border_width            2
bspc config window_gap              6
bspc config top_padding             0
bspc config bottom_padding          0
bspc config left_padding            0
bspc config right_padding           0

bspc config normal_border_color     '#4B4B4B'
bspc config focused_border_color    '#c1e1c1'
# bspc config focused_border_color    '#bd93f9'

bspc config split_ratio             0.5
bspc config borderless_monocle      true
bspc config gapless_monocle         false

bspc rule -a Zathura state=tiled
bspc rule -a zoom state=floating

~/.fehbg
~/.config/polybar/launch.sh --shades &
# killall nm-applet
# nm-applet &
# killall blueman-applet
# blueman-applet &
killall picom
picom &
