#!/bin/bash

for file in "$@"; do
    if ! grep config_file_path $file > /dev/null; then
        echo "$file does not have 'config_file_path=<path>', aborting"
        exit 1
    fi

    src=$(realpath $file)
    dst=$(grep config_file_path $file | cut -d = -f 2 | cut -d ' ' -f 1)
    dst=${dst/#\~/$HOME}    # manually expand tilde
    mkdir -p $(dirname $dst)

    err=$(ln -sf $src $dst 2>&1)
    if [[ $err == *'Permission denied'* ]]; then
        sudo ln -sf $src $dst
    elif [[ -n $err ]]; then
        echo $err
        exit 1
    fi
done
