#!/bin/bash
# ~/.config/rofi/save_scrot

cd $HOME/Documents
latest_search=''
if test -f ".latest_search.txt"; then
    latest_search=`cat .latest_search.txt`
fi
dirs=`find . -type d | tail -n +2 | cut -c 3-`
chosen=$(echo -e "$dirs" | rofi -dmenu -i -p -filter "$latest_search")
maim -s $chosen
echo -n "$chosen" | xclip -sel c
echo -n "$chosen" > .latest_search.txt
