# Put the following lines in your ~/.config/kitty/kitty.conf
foreground #e1d9ea
background #0f0f10
color0 #74745d
color1 #e3e3a8
color2 #56417a
color3 #aeae98
color4 #7b6c97
color5 #666655
color6 #dfdfa9
color7 #a39778
color8 #74745d
color9 #cd749c
color10 #a38c78
color11 #bbbc57
color12 #bbbc57
color13 #424234
color14 #a2a284
color15 #d9d9cf
cursor #7b6c97
cursor_text_color #282822
selection_foreground none
selection_background #383815
tab_bar_background #080808
active_tab_foreground #e1d9ea
active_tab_background #0f0f10
inactive_tab_foreground #9a9a66
inactive_tab_background #0b0b0c
active_border_color #a38c78
inactive_border_color #282822

font_size               11.5
hide_window_decorations no
modify_font cell_width  100%
placement_strategy      bottom

# BEGIN_KITTY_FONTS
font_family      family="Ioskeley Mono"
bold_font        family='Ioskeley Mono' style=Bold
italic_font      auto
bold_italic_font family='Ioskeley Mono' style='Bold Italic'
# END_KITTY_FONTS
