# Put the following lines in your ~/.config/kitty/kitty.conf
foreground #171412
background #c9c9c9
color0 #2e2e2e
color1 #8c0e0e
color2 #2b4d28
color3 #4b4619
color4 #0f467c
color5 #5d1ba8
color6 #264b47
color7 #362e0b
color8 #332d28
color9 #8c0e0e
color10 #294d24
color11 #663a0f
color12 #1b4a5d
color13 #5c1ca9
color14 #264b46
color15 #332e1b
cursor #5a5116
cursor_text_color #c9c9c9
selection_foreground none
selection_background #aaaaaa
tab_bar_background #a0a0a0
active_tab_foreground #171412
active_tab_background #c9c9c9
inactive_tab_foreground #58554b
inactive_tab_background #b0b0b0
active_border_color #c9c9c9
inactive_border_color #4c492d

font_size               13
hide_window_decorations no
modify_font cell_width  100%
placement_strategy      bottom

# BEGIN_KITTY_FONTS
font_family      family='Geist Mono' variable_name=GeistMono wght=450
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
