#!/bin/sh
# ~/.config/openbox/autostart
#
# These things are run when an Openbox X Session is started.
# You may place a similar script in $HOME/.config/openbox/autostart
# to run user-specific things.
#

# If you want to use GNOME config tools...
#
#if test -x /usr/libexec/gnome-settings-daemon >/dev/null; then
#  /usr/libexec/gnome-settings-daemon &
#elif which gnome-settings-daemon >/dev/null; then
#  gnome-settings-daemon &
#fi

# If you want to use XFCE config tools...
#
#xfce-mcs-manager &

if [[ $(xrandr | grep 'HDMI-1') == *'disconnected'* ]]; then
    echo 'disconnected'
    xrandr --output HDMI-1 --off
else
    echo 'connected'
    xrandr --output HDMI-1 --right-of eDP-1 --auto
fi

xset r rate 250 45
feh --randomize --bg-fill ~/Pictures/bulksplash/*
~/.config/polybar/material/scripts/random.sh
~/.config/polybar/launch.sh --material &
killall nm-applet
nm-applet &
