#
# General
#

set -g default-shell /usr/bin/zsh
set -g escape-time 0
set -g history-limit 1000000
set -g mode-keys vi
set -g prefix C-a

bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

#
# Theme
#

# Copy this to your tmux.conf
set -g status-style "bg=#08111c,fg=#f5f5dc"
set -g status-left "#[bg=#08111c]#[fg=#f5f5dc] #S "
set -g status-left-length 100
set -g status-right "#[bg=#08111c]#[fg=#f5f5dc] #(date) "
setw -g window-status-style fg="#f5f5dc",bg="#08111c"
setw -g window-status-current-style fg="#808a96",bg="#273b54"
setw -g window-status-format " #I #W "
setw -g window-status-current-format " #I #W "
setw -g window-status-separator ""
